languageCode = 'en-us'
title = 'Timo'
theme = 'hugo-theme-console'

[params]

[[params.navlinks]]
name = "about/"
url = "/about"

[[params.navlinks]]
name = "logbook/"
url = "/logbook"

[[params.navlinks]]
name = "music/"
url = "/music"

[[params.navlinks]]
name = "â‚¿/"
url = "/bitcoin.pdf"
